version: '3.9'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 #--broadcast-address=127.0.0.1 #example for debugging locally
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

  calculator:
    build:
      context: ./src
      dockerfile: calculator/Dockerfile.server
    depends_on:
      - nsqd
      - nsqlookupd
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: ":8000"
      NSQ_ADDR: "nsqd:4150"

  viewer-cli:
    build:
      context: ./src
      dockerfile: viewer/Dockerfile.cli
    depends_on:
      - nsqd
      - nsqlookupd
    environment:
      NSQLOOKUPD_ADDR: "nsqlookupd:4161"
